# Generated by Django 6.0.6 on 2026-06-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(choices=[('white', 'WHITE'), ('blue', ' BLUE'), ('black', 'BLACK'), ('red', 'RED'), ('green', 'GREEN'), ('yellow', 'YELLOW'), ('purple', 'PURPLE'), ('orange', 'ORANGE'), ('pink', 'PINK'), ('gray', 'GRAY'), ('brown', 'BROWN')], max_length=100)),
                ('image', models.ImageField(blank=True, default='/default_watch.jpg', upload_to='watch/')),
            ],
        ),
    ]
